export type QuestionType =
  | "text"
  | "textarea"
  | "single"
  | "multi"
  | "scale";

export type Question = {
  id: string;
  section: string;
  eyebrow: string;
  title: string;
  description?: string;
  type: QuestionType;
  placeholder?: string;
  required?: boolean;
  options?: string[];
  maxSelections?: number;
  leftLabel?: string;
  rightLabel?: string;
};

export const questionnaireSections = [
  "Business",
  "Goals",
  "Audience",
  "Positioning",
  "Personality",
  "Visual",
  "Voice",
  "Final",
];

export const questions: Question[] = [
  {
    id: "brandName",
    section: "Business",
    eyebrow: "Your Business",
    title: "What is the name of your brand?",
    type: "text",
    placeholder: "Your brand or business name",
    required: true,
  },
  {
    id: "website",
    section: "Business",
    eyebrow: "Your Business",
    title: "Do you currently have a website?",
    description: "Leave this blank if you do not have one yet.",
    type: "text",
    placeholder: "https://example.com",
  },
  {
    id: "businessDescription",
    section: "Business",
    eyebrow: "Your Business",
    title: "What does your business do?",
    description:
      "Explain it naturally, as if you were introducing the business to someone for the first time.",
    type: "textarea",
    placeholder: "Tell us about the business...",
    required: true,
  },
  {
    id: "offers",
    section: "Business",
    eyebrow: "Your Business",
    title: "What are your main products or services?",
    type: "textarea",
    placeholder: "List your primary offers...",
    required: true,
  },
  {
    id: "originStory",
    section: "Business",
    eyebrow: "Your Business",
    title: "Why was this business created?",
    description:
      "Tell us about the idea, problem, experience, or opportunity that started it.",
    type: "textarea",
    placeholder: "Share the story behind the business...",
    required: true,
  },

  {
    id: "brandingGoals",
    section: "Goals",
    eyebrow: "Brand Goals",
    title: "What should better branding help you accomplish?",
    description: "Choose everything that matters.",
    type: "multi",
    required: true,
    options: [
      "Look more professional",
      "Attract premium clients",
      "Increase credibility",
      "Increase prices",
      "Differentiate from competitors",
      "Build stronger recognition",
      "Modernize the brand",
      "Prepare for growth",
      "Launch something new",
      "Create consistency",
    ],
  },
  {
    id: "priority",
    section: "Goals",
    eyebrow: "Brand Goals",
    title: "What is the single most important outcome?",
    type: "textarea",
    placeholder: "If this project succeeds, what changes?",
    required: true,
  },
  {
    id: "vision",
    section: "Goals",
    eyebrow: "Brand Goals",
    title: "Where do you want the brand to be five years from now?",
    type: "textarea",
    placeholder: "Describe the future you are building toward...",
    required: true,
  },

  {
    id: "idealCustomer",
    section: "Audience",
    eyebrow: "Your Audience",
    title: "Describe your ideal customer.",
    description:
      "Think about their lifestyle, needs, priorities, personality, ambitions, and buying behavior.",
    type: "textarea",
    placeholder: "The type of customer you would love to attract more of...",
    required: true,
  },
  {
    id: "customerProblem",
    section: "Audience",
    eyebrow: "Your Audience",
    title: "What problem are they trying to solve?",
    type: "textarea",
    placeholder: "What is frustrating, difficult, missing, or unresolved?",
    required: true,
  },
  {
    id: "customerAfter",
    section: "Audience",
    eyebrow: "Your Audience",
    title: "How should customers feel after experiencing your brand?",
    description: "Choose up to four.",
    type: "multi",
    maxSelections: 4,
    required: true,
    options: [
      "Confident",
      "Inspired",
      "Empowered",
      "Calm",
      "Understood",
      "Excited",
      "Sophisticated",
      "Secure",
      "Proud",
      "Energized",
      "Connected",
      "Transformed",
    ],
  },

  {
    id: "competitors",
    section: "Positioning",
    eyebrow: "Positioning",
    title: "Who are your closest competitors or alternatives?",
    description:
      "Names or website links are both useful. They do not need to be exact competitors.",
    type: "textarea",
    placeholder: "Competitor names, links, or alternatives...",
    required: true,
  },
  {
    id: "differentiator",
    section: "Positioning",
    eyebrow: "Positioning",
    title: "Why should someone choose you instead?",
    description:
      "What do you do, believe, deliver, or understand differently?",
    type: "textarea",
    placeholder: "What makes your business meaningfully different?",
    required: true,
  },
  {
    id: "marketPosition",
    section: "Positioning",
    eyebrow: "Positioning",
    title: "Where should the brand sit in the market?",
    type: "single",
    required: true,
    options: [
      "Accessible",
      "Mid-market",
      "Premium",
      "High-end",
      "Luxury",
      "Ultra-luxury",
    ],
  },
  {
    id: "knownFor",
    section: "Positioning",
    eyebrow: "Positioning",
    title: "What is the one idea you want this brand to own?",
    description:
      "Complete the thought: When people think about ______, I want them to think about us.",
    type: "textarea",
    placeholder: "The idea, expertise, experience, or category you want to own...",
    required: true,
  },

  {
    id: "personality",
    section: "Personality",
    eyebrow: "Brand Personality",
    title: "Choose the characteristics that should define the future brand.",
    description: "Choose up to six.",
    type: "multi",
    maxSelections: 6,
    required: true,
    options: [
      "Sophisticated",
      "Refined",
      "Bold",
      "Warm",
      "Editorial",
      "Artistic",
      "Luxurious",
      "Minimal",
      "Timeless",
      "Modern",
      "Playful",
      "Intelligent",
      "Confident",
      "Human",
      "Cinematic",
      "Innovative",
      "Grounded",
      "Exclusive",
    ],
  },
  {
    id: "modernity",
    section: "Personality",
    eyebrow: "Brand Personality",
    title: "Where should the brand sit between traditional and modern?",
    type: "scale",
    required: true,
    leftLabel: "Traditional",
    rightLabel: "Modern",
  },
  {
    id: "expression",
    section: "Personality",
    eyebrow: "Brand Personality",
    title: "How expressive should the identity feel?",
    type: "scale",
    required: true,
    leftLabel: "Minimal",
    rightLabel: "Expressive",
  },
  {
    id: "exclusivity",
    section: "Personality",
    eyebrow: "Brand Personality",
    title: "How exclusive should the brand feel?",
    type: "scale",
    required: true,
    leftLabel: "Accessible",
    rightLabel: "Exclusive",
  },

  {
    id: "visualStyles",
    section: "Visual",
    eyebrow: "Visual Direction",
    title: "Which visual directions feel right?",
    description: "Choose up to five.",
    type: "multi",
    maxSelections: 5,
    required: true,
    options: [
      "Editorial",
      "Minimal",
      "Luxury",
      "Organic",
      "Contemporary",
      "Cinematic",
      "Bold",
      "Timeless",
      "Artistic",
      "Architectural",
      "Playful",
      "Experimental",
      "Fashion-inspired",
      "Monochromatic",
      "High contrast",
    ],
  },
  {
    id: "colors",
    section: "Visual",
    eyebrow: "Visual Direction",
    title: "Are there colors or color families you are naturally drawn to?",
    type: "textarea",
    placeholder:
      "Describe colors you love, existing brand colors, or simply write 'open to direction'.",
  },
  {
    id: "visualAvoid",
    section: "Visual",
    eyebrow: "Visual Direction",
    title: "What should the brand never look like?",
    description:
      "Think about colors, styles, clichés, competitors, typography, or anything else you strongly dislike.",
    type: "textarea",
    placeholder: "Styles, colors, trends, or visual ideas to avoid...",
    required: true,
  },

  {
    id: "voice",
    section: "Voice",
    eyebrow: "Brand Voice",
    title: "How should the brand communicate?",
    description: "Choose up to six.",
    type: "multi",
    maxSelections: 6,
    required: true,
    options: [
      "Professional",
      "Conversational",
      "Sophisticated",
      "Friendly",
      "Intelligent",
      "Inspirational",
      "Direct",
      "Playful",
      "Calm",
      "Confident",
      "Editorial",
      "Authoritative",
      "Compassionate",
      "Provocative",
      "Minimal",
    ],
  },
  {
    id: "tone",
    section: "Voice",
    eyebrow: "Brand Voice",
    title: "Where should the communication sit between formal and casual?",
    type: "scale",
    required: true,
    leftLabel: "Formal",
    rightLabel: "Casual",
  },
  {
    id: "inspiration",
    section: "Voice",
    eyebrow: "References",
    title: "Which brands, websites, or creative references inspire you?",
    description:
      "Include links if possible and tell us briefly what you like about them.",
    type: "textarea",
    placeholder: "Brands, websites, designers, spaces, publications...",
  },

  {
    id: "neverFeel",
    section: "Final",
    eyebrow: "Final Thoughts",
    title: "What should your brand never feel like?",
    type: "textarea",
    placeholder: "Cheap, corporate, generic, childish, cold, confusing...",
    required: true,
  },
  {
    id: "finalLove",
    section: "Final",
    eyebrow: "Final Thoughts",
    title: "What would make you absolutely love the finished brand?",
    description:
      "This can be strategic, emotional, visual, or simply something you hope the final identity achieves.",
    type: "textarea",
    placeholder: "Tell us what a successful creative direction would feel like...",
    required: true,
  },
];